### ISSUE TITLE
add styling to links in vue-apps

### ISSUE THREAD

**Issue by blairmacintyre** [realitymediabook/vue-apps#40]
There is no styling on links in vue apps.  

Add CSS for appearance
Add hover for appearance
make xr-layer

**Comment by blairmacintyre** [comment]
Issue with styled link popping out of html

**Comment by blairmacintyre** [comment]
seems to work if correct html used.  Need to put the xr-layer on the closest enclosing div.

**Comment by jspark474** [comment]
I see where you attach the xr-layer to. But when I see the app in the room, the hovering over and clicking on the links are not working.
