### ISSUE TITLE
problem with the vue-app that draws a link on the right wall of Arrival Hall

### ISSUE THREAD

**Issue by jdbolter** [realitymediabook/vue-apps#44]
![arrival-hall-link](https://user-images.githubusercontent.com/2444791/155607348-0f634516-ca86-4daf-8afa-004c94a5cf2a.png)

**Comment by blairmacintyre** [comment]
The problem is the <a> is inside a div marked with absolute position.

Right now, it's only really safe to put "xr-layer" on div and img/video/canvas tags.  so, I moved the xr-layer to the full div.  Testing

**Comment by blairmacintyre** [comment]
fixed.
