### ISSUE TITLE
Clicking on links not working properly

### ISSUE THREAD

**Issue by blairmacintyre** [realitymediabook/vue-apps#45]
There is a bug in ethereal that is causing the wrong locations to be used inside a weblayer for clicking.  So, clicking on a link doesn't work most of the time.

This is being looked into

**Comment by soysoyee** [comment]
Onboarding Room - Some links not working:

two links under "The Hubs Platform"(highlighted/underlined)

1) Hubs user documentation
2) list of Hubs Control

**Comment by soysoyee** [comment]
Acropolis - Broken media link

"Click the link to go back to the website"
<img width="1081" alt="Screen Shot 2022-03-29 at 3 09 19 PM" src="https://user-images.githubusercontent.com/42994667/160688776-3d51a5d9-1c22-49ac-962a-b1746bbc5c7c.png">

**Comment by blairmacintyre** [comment]
Many of them should be fixed, there's still a bug, but if we don't have links inside xr-layers, it should work.

**Comment by blairmacintyre** [comment]
Seems to work now.
