### ISSUE TITLE
Texts are floating in front of monoliths in Rotunda

### ISSUE THREAD

**Issue by jdbolter** [realitymediabook/vue-apps#46]

**Comment by jdbolter** [comment]
I'm using Chrome on a Mac and the name texts for the rooms float perhaps .5 meters in front of the column

**Comment by blairmacintyre** [comment]
This is probably a result of me "fixing" the way label positions were handled to deal with that nesting groups issue with portals.

They probably need to be edited in the scene, sorry

**Comment by blairmacintyre** [comment]
@jspark474 you will probably need to adjust the title's over the portals anywhere you used them ... :(

**Comment by jspark474** [comment]
@blairmacintyre Thank you for letting me know! I just fixed them :)
