### ISSUE TITLE
System error: sometimes the screen freezes when going into a new portal(have to refresh the page to get in)

### ISSUE THREAD

**Issue by soyjang** [realitymediabook/vue-apps#75]
<img width="699" alt="portal" src="https://user-images.githubusercontent.com/42994667/163578620-47008a0d-3888-4487-b357-5d1057bd8a09.png">

**Comment by blairmacintyre** [comment]
Can you provide more detail on this?  What do you mean by "freezes"?  I have not seen this.  What browser?  How to recreate it?

**Comment by soyjang** [comment]
> Can you provide more detail on this? What do you mean by "freezes"? I have not seen this. What browser? How to recreate it?

This occurred to one of our participants during UT. For her, going into rooms(Acropolis, Pitfall experiment) from the Presence gallery didn't work. The screen froze like the image I attached in the description and she got stuck on the loading bar. I think she was using safari.

**Comment by blairmacintyre** [comment]
hmm.  I see this too but have no idea why it's doing it.  refreshing doesn't let me in these rooms.

**Comment by blairmacintyre** [comment]
fixed by exiting to 2D first, and/or fading to white.   Don't use Safari.
