### ISSUE TITLE
text boxes don't fit frames in Pit room

### ISSUE THREAD

**Issue by blairmacintyre** [realitymediabook/vue-apps#77]
Most of the text boxes are too big.

**Comment by jspark474** [comment]
Text boxes appear that they fit the frame. Do you mean that the font sizes are too big?

**Comment by blairmacintyre** [comment]
They look like this to me.  Let me flush my cache and see if they fit when they rebuild

![image](https://user-images.githubusercontent.com/1348861/163839921-1e296d76-018e-4670-ba51-241bd6290ec7.png)

**Comment by blairmacintyre** [comment]
Oh, I bet it's the newer version of ethereal that got pushed recently.  There were some formatting bugs that go fixed, which may change some rendering ... you should probably do a quick walk everyone to see if there are issues.
